---
name: main

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node:
          - '12'
          - '14'
          - '16'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node:
          - '12'
          - '14'
          - '16'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node:
          - '12'
          - '14'
          - '16'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
