---
name: publish

on:
  push:
    tags:
      - v*

jobs:
  npm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: '12'
      - name: Build
        run: npn run build
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
  github:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: '12'
      - name: Build
        run: npm run build
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com
