---
name: publish

on:
  push:
    tags:
      - v*

jobs:
  npm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: '12'
          registry_url: https://registry.npmjs.org
      - name: Check version
        id: version
        run: |
          echo "::set-output name=name::$(jq -r '.name' package.json)"
          echo "::set-output name=current::$(jq -r '.version' package.json)"
          echo "::set-output name=published::$(npm view $(jq -r '.name' package.json)@$(jq -r '.version' package.json) version)"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build
        run: npn run build
      - name: Publish ${{ steps.version.outputs.name }}@${{ steps.version.outputs.current }}
        if: ${{ endsWith(github.ref, format('v{0}', steps.version.outputs.published)) == false }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  github:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: '12'
          registry_url: https://npm.pkg.github.com
      - name: Check version
        id: version
        run: |
          echo "::set-output name=name::$(jq -r '.name' package.json)"
          echo "::set-output name=current::$(jq -r '.version' package.json)"
          echo "::set-output name=published::$(npm view $(jq -r '.name' package.json)@$(jq -r '.version' package.json) version)"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: npm run build
      - name: Publish ${{ steps.version.outputs.name }}@${{ steps.version.outputs.current }}
        if: ${{ endsWith(github.ref, format('v{0}', steps.version.outputs.published)) == false }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
