---
name: publish

on:
  push:
    tags:
      - v*

jobs:
  npm:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        id: import_gpg
        with:
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-committer-name: ${{ secrets.GIT_USER_NAME }}
          git-committer-email: ${{ secrets.GIT_USER_EMAIL }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Get version
        id: version
        run: echo "{current}=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
      - name: Documentation
        run: npm run docs:build
      - name: Publish ${{ steps.version.outputs.current }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .docs
          destination_dir: ${{ steps.version.outputs.current }}
          keep_files: true
          user_name: ${{ secrets.GIT_USER_NAME }}
          user_email: ${{ secrets.GIT_USER_EMAIL }}
      - name: Publish latest
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .docs
          keep_files: true
          user_name: ${{ secrets.GIT_USER_NAME }}
          user_email: ${{ secrets.GIT_USER_EMAIL }}
